nama = input("Masukkan nama: ")
umur = input("Masukkan umur: ")
alamat = input("Masukkan alamat: ")
print("\n-------Biodata-------")
print("Nama: " + nama)
print("Umur: " + umur)
print("Alamat: " + alamat)
