nama = input("Masukkan nama: ")
umur = input("Masukkan umur: ")
alamat = input("Masukkan alamat: ")
Jurusan= input("Masukkan Jurusan: ")

print("\n-------Biodata-------")
print("Nama: " + nama)
print("Umur: " + umur)
print("Alamat: " + alamat)
print("Jurusan: " + Jurusan)
